name: "Push-to-GitHub-registry"

on:
  push:
    branches:
      - main
env:
  TAG: "latest"

jobs:
  my-docker:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        
      - name: "Login GitHub registry"
        run: run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: "Build"
        run: docker build -t ghcr.io/sivin79/push_gh_registry2:${{ env.TAG }} .
        
      - name: "Push"
        run: docker push ghcr.io/sivin79/push_gh_registry2:${{ env.TAG }}
